# -*- coding: utf-8 -*-
"""Named_Entity_Recognition_(NER)_and_Sentence_Completion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130pNez2dsCovEU6Zk0cLFJJx8J9C5IUE
"""

!pip install streamlit transformers torch

!pip install streamlit transformers torch pyngrok

!pip install pyngrok

!ngrok authtoken 2mhQV1wAiIYK35sfVMN2qT2PUoc_852LFF1mGbxpaJatrgjfn # Replace <YOUR_AUTHTOKEN>

from pyngrok import ngrok

# Set your authtoken
ngrok.set_auth_token("2mhQV1wAiIYK35sfVMN2qT2PUoc_852LFF1mGbxpaJatrgjfn") # Replace <YOUR_AUTHTOKEN>

# Terminate any existing tunnels
ngrok.kill()

# Start a new tunnel for Streamlit
# Use addr instead of port
public_url = ngrok.connect(addr='8501')
public_url

!streamlit run NER.py &>/dev/null&

print(f"Streamlit app is live at: {public_url}")

import requests
import base64

# GitHub API endpoint
github_api_url = 'https://api.github.com/repos/<owner>/<repo>/actions/workflows/<workflow_id>/dispatches'

# GitHub Personal Access Token
token = 'YOUR_GITHUB_PERSONAL_ACCESS_TOKEN'

# Encoded personal access token
token = base64.b64encode(token.encode('utf-8')).decode('utf-8')

# Headers for the GitHub API request
headers = {
    'Authorization': f'Basic {token}',
    'Accept': 'application/vnd.github.v3+json'
}

# Data for the POST request
data = {
    'ref': 'main'
}

# Make a POST request to trigger the GitHub action
response = requests.post(github_api_url, headers=headers, json=data)

# Check the response status
if response.status_code == 204:
    print('GitHub Action triggered successfully!')
else:
    print(f'Failed to trigger GitHub Action. Status code: {response.status_code}')

!git config --global user.name "doaanas"
!git config --global user.email "doaanasram@gmail.com"
!git config --global user.password "d03071997n!"

token = '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'
username = 'doaanas'
repo = '-Named-Entity-Recognition-NER-and-Sentence-Completion-'

!git clone https://{token}@github.com/{username}/{repo}

!apt-get install git

!git config --global --unset user.password

!git clone https://{token}@github.com/{username}/{repo}

!git ls-remote https://github.com/<username>/<repo>.git

# Commented out IPython magic to ensure Python compatibility.
# %cd {repo}