name: Deploy Streamlit App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit transformers torch pyngrok

    - name: Authenticate with Ngrok
      run: |
        echo 2mhQV1wAiIYK35sfVMN2qT2PUoc_852LFF1mGbxpaJatrgjfn > ~/.ngrok_token
        pyngrok authtoken 2mhQV1wAiIYK35sfVMN2qT2PUoc_852LFF1mGbxpaJatrgjfn

    - name: Run Streamlit app
      run: |
        ngrok authtoken 2mhQV1wAiIYK35sfVMN2qT2PUoc_852LFF1mGbxpaJatrgjfn
        streamlit run NER.py --server.port 8501

    - name: Trigger GitHub Action
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches \
        -d '{"ref": "main"}'

    - name: Notify URL
      run: |
        echo "Streamlit app is live at $(curl --silent http://localhost:4040/api/tunnels | jq .tunnels[0].public_url)"
