name: Deploy Streamlit App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'  # Adjust Python version if necessary

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit transformers torch

    - name: Run Streamlit app
      run: |
        streamlit run your_script_name.py --server.port 8501 > streamlit_output.log 2>&1 &
        sleep 10  # Wait for Streamlit to start up

    - name: Check Streamlit logs
      run: |
        cat streamlit_output.log

    - name: Notify URL
      run: |
        echo "Streamlit app should be live at http://localhost:8501"
